import colors from './tokens.js';

const theme = {
    md_sys_color_primary: colors.md_sys_color_primary_dark,
    md_sys_color_on_primary: colors.md_sys_color_on_primary_dark,
    md_sys_color_primary_container: colors.md_sys_color_primary_container_dark,
    md_sys_color_on_primary_container: colors.md_sys_color_on_primary_container_dark,
    md_sys_color_secondary: colors.md_sys_color_secondary_dark,
    md_sys_color_on_secondary: colors.md_sys_color_on_secondary_dark,
    md_sys_color_secondary_container: colors.md_sys_color_secondary_container_dark,
    md_sys_color_on_secondary_container: colors.md_sys_color_on_secondary_container_dark,
    md_sys_color_tertiary: colors.md_sys_color_tertiary_dark,
    md_sys_color_on_tertiary: colors.md_sys_color_on_tertiary_dark,
    md_sys_color_tertiary_container: colors.md_sys_color_tertiary_container_dark,
    md_sys_color_on_tertiary_container: colors.md_sys_color_on_tertiary_container_dark,
    md_sys_color_error: colors.md_sys_color_error_dark,
    md_sys_color_error_container: colors.md_sys_color_error_container_dark,
    md_sys_color_on_error: colors.md_sys_color_on_error_dark,
    md_sys_color_on_error_container: colors.md_sys_color_on_error_container_dark,
    md_sys_color_background: colors.md_sys_color_background_dark,
    md_sys_color_on_background: colors.md_sys_color_on_background_dark,
    md_sys_color_surface: colors.md_sys_color_surface_dark,
    md_sys_color_on_surface: colors.md_sys_color_on_surface_dark,
    md_sys_color_surface_variant: colors.md_sys_color_surface_variant_dark,
    md_sys_color_on_surface_variant: colors.md_sys_color_on_surface_variant_dark,
    md_sys_color_outline: colors.md_sys_color_outline_dark,
    md_sys_color_inverse_on_surface: colors.md_sys_color_inverse_on_surface_dark,
    md_sys_color_inverse_surface: colors.md_sys_color_inverse_surface_dark,
    md_sys_color_inverse_primary: colors.md_sys_color_inverse_primary_dark,
    md_sys_color_shadow: colors.md_sys_color_shadow_dark,
    md_sys_color_surface_tint: colors.md_sys_color_surface_tint_dark,
    md_sys_color_outline_variant: colors.md_sys_color_outline_variant_dark,
    md_sys_color_scrim: colors.md_sys_color_scrim_dark,
}

export default theme;