import { Roboto_400Regular, Roboto_500Medium } from '@expo-google-fonts/roboto'

const tokens = {
    md_source: "#929000",
    /* primary */
    md_ref_palette_primary0: "#000000",
    md_ref_palette_primary10: "#1d1d00",
    md_ref_palette_primary20: "#333200",
    md_ref_palette_primary25: "#3e3d00",
    md_ref_palette_primary30: "#4a4900",
    md_ref_palette_primary35: "#565500",
    md_ref_palette_primary40: "#636100",
    md_ref_palette_primary50: "#7c7b00",
    md_ref_palette_primary60: "#97950a",
    md_ref_palette_primary70: "#b2b02c",
    md_ref_palette_primary80: "#cecc47",
    md_ref_palette_primary90: "#ebe860",
    md_ref_palette_primary95: "#f9f76d",
    md_ref_palette_primary98: "#fffcc7",
    md_ref_palette_primary99: "#fffbff",
    md_ref_palette_primary100: "#ffffff",
    /* secondary */
    md_ref_palette_secondary0: "#000000",
    md_ref_palette_secondary10: "#1d1d06",
    md_ref_palette_secondary20: "#323218",
    md_ref_palette_secondary25: "#3d3d22",
    md_ref_palette_secondary30: "#49482d",
    md_ref_palette_secondary35: "#555437",
    md_ref_palette_secondary40: "#616042",
    md_ref_palette_secondary50: "#7a7859",
    md_ref_palette_secondary60: "#949271",
    md_ref_palette_secondary70: "#afad8a",
    md_ref_palette_secondary80: "#cbc8a4",
    md_ref_palette_secondary90: "#e7e4bf",
    md_ref_palette_secondary95: "#f6f2cc",
    md_ref_palette_secondary98: "#fefbd5",
    md_ref_palette_secondary99: "#fffbff",
    md_ref_palette_secondary100: "#ffffff",
    /* tertiary */
    md_ref_palette_tertiary0: "#000000",
    md_ref_palette_tertiary10: "#002116",
    md_ref_palette_tertiary20: "#0c3729",
    md_ref_palette_tertiary25: "#194334",
    md_ref_palette_tertiary30: "#264e3f",
    md_ref_palette_tertiary35: "#325a4a",
    md_ref_palette_tertiary40: "#3e6656",
    md_ref_palette_tertiary50: "#567f6e",
    md_ref_palette_tertiary60: "#709a87",
    md_ref_palette_tertiary70: "#8ab4a1",
    md_ref_palette_tertiary80: "#a4d0bc",
    md_ref_palette_tertiary90: "#c0ecd7",
    md_ref_palette_tertiary95: "#cefbe5",
    md_ref_palette_tertiary98: "#e7fff2",
    md_ref_palette_tertiary99: "#f4fff7",
    md_ref_palette_tertiary100: "#ffffff",
    /* neutral */
    md_ref_palette_neutral0: "#000000",
    md_ref_palette_neutral10: "#1c1c16",
    md_ref_palette_neutral20: "#31302b",
    md_ref_palette_neutral25: "#3d3b35",
    md_ref_palette_neutral30: "#484741",
    md_ref_palette_neutral35: "#54524c",
    md_ref_palette_neutral40: "#605e58",
    md_ref_palette_neutral50: "#797770",
    md_ref_palette_neutral60: "#939189",
    md_ref_palette_neutral70: "#aeaba3",
    md_ref_palette_neutral80: "#c9c6be",
    md_ref_palette_neutral90: "#e6e2d9",
    md_ref_palette_neutral95: "#f4f0e7",
    md_ref_palette_neutral98: "#fdf9f0",
    md_ref_palette_neutral99: "#fffbff",
    md_ref_palette_neutral100: "#ffffff",
    /* neutral_variant */
    md_ref_palette_neutral_variant0: "#000000",
    md_ref_palette_neutral_variant10: "#1d1c11",
    md_ref_palette_neutral_variant20: "#323125",
    md_ref_palette_neutral_variant25: "#3d3c2f",
    md_ref_palette_neutral_variant30: "#48473a",
    md_ref_palette_neutral_variant35: "#545345",
    md_ref_palette_neutral_variant40: "#605f51",
    md_ref_palette_neutral_variant50: "#797869",
    md_ref_palette_neutral_variant60: "#939181",
    md_ref_palette_neutral_variant70: "#aeac9b",
    md_ref_palette_neutral_variant80: "#cac7b6",
    md_ref_palette_neutral_variant90: "#e6e3d1",
    md_ref_palette_neutral_variant95: "#f5f1df",
    md_ref_palette_neutral_variant98: "#fdfae7",
    md_ref_palette_neutral_variant99: "#fffbff",
    md_ref_palette_neutral_variant100: "#ffffff",
    /* error */
    md_ref_palette_error0: "#000000",
    md_ref_palette_error10: "#410002",
    md_ref_palette_error20: "#690005",
    md_ref_palette_error25: "#7e0007",
    md_ref_palette_error30: "#93000a",
    md_ref_palette_error35: "#a80710",
    md_ref_palette_error40: "#ba1a1a",
    md_ref_palette_error50: "#de3730",
    md_ref_palette_error60: "#ff5449",
    md_ref_palette_error70: "#ff897d",
    md_ref_palette_error80: "#ffb4ab",
    md_ref_palette_error90: "#ffdad6",
    md_ref_palette_error95: "#ffedea",
    md_ref_palette_error98: "#fff8f7",
    md_ref_palette_error99: "#fffbff",
    md_ref_palette_error100: "#ffffff",
    /* light */
    md_sys_color_primary_light: "#636100",
    md_sys_color_on_primary_light: "#ffffff",
    md_sys_color_primary_container_light: "#ebe860",
    md_sys_color_on_primary_container_light: "#1d1d00",
    md_sys_color_secondary_light: "#616042",
    md_sys_color_on_secondary_light: "#ffffff",
    md_sys_color_secondary_container_light: "#e7e4bf",
    md_sys_color_on_secondary_container_light: "#1d1d06",
    md_sys_color_tertiary_light: "#3e6656",
    md_sys_color_on_tertiary_light: "#ffffff",
    md_sys_color_tertiary_container_light: "#c0ecd7",
    md_sys_color_on_tertiary_container_light: "#002116",
    md_sys_color_error_light: "#ba1a1a",
    md_sys_color_error_container_light: "#ffdad6",
    md_sys_color_on_error_light: "#ffffff",
    md_sys_color_on_error_container_light: "#410002",
    md_sys_color_background_light: "#fffbff",
    md_sys_color_on_background_light: "#1c1c16",
    md_sys_color_surface_light: "#fffbff",
    md_sys_color_on_surface_light: "#1c1c16",
    md_sys_color_surface_variant_light: "#e6e3d1",
    md_sys_color_on_surface_variant_light: "#48473a",
    md_sys_color_outline_light: "#797869",
    md_sys_color_inverse_on_surface_light: "#f4f0e7",
    md_sys_color_inverse_surface_light: "#31302b",
    md_sys_color_inverse_primary_light: "#cecc47",
    md_sys_color_shadow_light: "#000000",
    md_sys_color_surface_tint_light: "#636100",
    md_sys_color_outline_variant_light: "#cac7b6",
    md_sys_color_scrim_light: "#000000",
    /* dark */
    md_sys_color_primary_dark: "#cecc47",
    md_sys_color_on_primary_dark: "#333200",
    md_sys_color_primary_container_dark: "#4a4900",
    md_sys_color_on_primary_container_dark: "#ebe860",
    md_sys_color_secondary_dark: "#cbc8a4",
    md_sys_color_on_secondary_dark: "#323218",
    md_sys_color_secondary_container_dark: "#49482d",
    md_sys_color_on_secondary_container_dark: "#e7e4bf",
    md_sys_color_tertiary_dark: "#a4d0bc",
    md_sys_color_on_tertiary_dark: "#0c3729",
    md_sys_color_tertiary_container_dark: "#264e3f",
    md_sys_color_on_tertiary_container_dark: "#c0ecd7",
    md_sys_color_error_dark: "#ffb4ab",
    md_sys_color_error_container_dark: "#93000a",
    md_sys_color_on_error_dark: "#690005",
    md_sys_color_on_error_container_dark: "#ffdad6",
    md_sys_color_background_dark: "#1c1c16",
    md_sys_color_on_background_dark: "#e6e2d9",
    md_sys_color_surface_dark: "#1c1c16",
    md_sys_color_on_surface_dark: "#e6e2d9",
    md_sys_color_surface_variant_dark: "#48473a",
    md_sys_color_on_surface_variant_dark: "#cac7b6",
    md_sys_color_outline_dark: "#939181",
    md_sys_color_inverse_on_surface_dark: "#1c1c16",
    md_sys_color_inverse_surface_dark: "#e6e2d9",
    md_sys_color_inverse_primary_dark: "#636100",
    md_sys_color_shadow_dark: "#000000",
    md_sys_color_surface_tint_dark: "#cecc47",
    md_sys_color_outline_variant_dark: "#48473a",
    md_sys_color_scrim_dark: "#000000",
    /* display _ large */
    md_sys_typescale_display_large_font_family_name: Roboto_400Regular,
    // md_sys_typescale_display_large_font_family_style: "Regular",
    // md_sys_typescale_display_large_font_weight: 400,
    md_sys_typescale_display_large_font_size: 57,
    md_sys_typescale_display_large_line_height: 64,
    md_sys_typescale_display_large_letter_spacing: 0.25,
    /* display _ medium */
    md_sys_typescale_display_medium_font_family_name: Roboto_400Regular,
    // md_sys_typescale_display_medium_font_family_style: "Regular",
    // md_sys_typescale_display_medium_font_weight: 400,
    md_sys_typescale_display_medium_font_size: 45,
    md_sys_typescale_display_medium_line_height: 52,
    md_sys_typescale_display_medium_letter_spacing: 0,
    /* display _ small */
    md_sys_typescale_display_small_font_family_name: Roboto_400Regular,
    // md_sys_typescale_display_small_font_family_style: "Regular",
    // md_sys_typescale_display_small_font_weight: 400,
    md_sys_typescale_display_small_font_size: 36,
    md_sys_typescale_display_small_line_height: 44,
    md_sys_typescale_display_small_letter_spacing: 0,
    /* headline _ large */
    md_sys_typescale_headline_large_font_family_name: Roboto_400Regular,
    // md_sys_typescale_headline_large_font_family_style: "Regular",
    // md_sys_typescale_headline_large_font_weight: 400,
    md_sys_typescale_headline_large_font_size: 32,
    md_sys_typescale_headline_large_line_height: 40,
    md_sys_typescale_headline_large_letter_spacing: 0,
    /* headline _ medium */
    md_sys_typescale_headline_medium_font_family_name: Roboto_400Regular,
    // md_sys_typescale_headline_medium_font_family_style: "Regular",
    // md_sys_typescale_headline_medium_font_weight: 400,
    md_sys_typescale_headline_medium_font_size: 28,
    md_sys_typescale_headline_medium_line_height: 36,
    md_sys_typescale_headline_medium_letter_spacing: 0,
    /* headline _ small */
    md_sys_typescale_headline_small_font_family_name: Roboto_400Regular,
    // md_sys_typescale_headline_small_font_family_style: "Regular",
    // md_sys_typescale_headline_small_font_weight: 400,
    md_sys_typescale_headline_small_font_size: 24,
    md_sys_typescale_headline_small_line_height: 32,
    md_sys_typescale_headline_small_letter_spacing: 0,
    /* body _ large */
    md_sys_typescale_body_large_font_family_name: Roboto_400Regular,
    // md_sys_typescale_body_large_font_family_style: "Regular",
    // md_sys_typescale_body_large_font_weight: 400,
    md_sys_typescale_body_large_font_size: 16,
    md_sys_typescale_body_large_line_height: 24,
    md_sys_typescale_body_large_letter_spacing: 0.50,
    /* body _ medium */
    md_sys_typescale_body_medium_font_family_name: Roboto_400Regular,
    // md_sys_typescale_body_medium_font_family_style: "Regular",
    // md_sys_typescale_body_medium_font_weight: 400,
    md_sys_typescale_body_medium_font_size: 14,
    md_sys_typescale_body_medium_line_height: 20,
    md_sys_typescale_body_medium_letter_spacing: 0.25,
    /* body _ small */
    md_sys_typescale_body_small_font_family_name: Roboto_400Regular,
    // md_sys_typescale_body_small_font_family_style: "Regular",
    // md_sys_typescale_body_small_font_weight: 400,
    md_sys_typescale_body_small_font_size: 12,
    md_sys_typescale_body_small_line_height: 16,
    md_sys_typescale_body_small_letter_spacing: 0.40,
    /* label _ large */
    md_sys_typescale_label_large_font_family_name: Roboto_500Medium,
    // md_sys_typescale_label_large_font_family_style: "Medium",
    // md_sys_typescale_label_large_font_weight: 500,
    md_sys_typescale_label_large_font_size: 14,
    md_sys_typescale_label_large_line_height: 20,
    md_sys_typescale_label_large_letter_spacing: 0.10,
    /* label _ medium */
    md_sys_typescale_label_medium_font_family_name: Roboto_500Medium,
    // md_sys_typescale_label_medium_font_family_style: "Medium",
    // md_sys_typescale_label_medium_font_weight: 500,
    md_sys_typescale_label_medium_font_size: 12,
    md_sys_typescale_label_medium_line_height: 16,
    md_sys_typescale_label_medium_letter_spacing: 0.50,
    /* label _ small */
    md_sys_typescale_label_small_font_family_name: Roboto_500Medium,
    // md_sys_typescale_label_small_font_family_style: "Medium",
    // md_sys_typescale_label_small_font_weight: 500,
    md_sys_typescale_label_small_font_size: 11,
    md_sys_typescale_label_small_line_height: 16,
    md_sys_typescale_label_small_letter_spacing: 0.50,
    /* title _ large */
    md_sys_typescale_title_large_font_family_name: Roboto_400Regular,
    // md_sys_typescale_title_large_font_family_style: "Regular",
    // md_sys_typescale_title_large_font_weight: 400,
    md_sys_typescale_title_large_font_size: 22,
    md_sys_typescale_title_large_line_height: 28,
    md_sys_typescale_title_large_letter_spacing: 0,
    /* title _ medium */
    md_sys_typescale_title_medium_font_family_name: Roboto_500Medium,
    // md_sys_typescale_title_medium_font_family_style: "Medium",
    // md_sys_typescale_title_medium_font_weight: 500,
    md_sys_typescale_title_medium_font_size: 16,
    md_sys_typescale_title_medium_line_height: 24,
    md_sys_typescale_title_medium_letter_spacing: 0.15,
    /* title _ small */
    md_sys_typescale_title_small_font_family_name: Roboto_500Medium,
    // md_sys_typescale_title_small_font_family_style: "Medium",
    // md_sys_typescale_title_small_font_weight: 500,
    md_sys_typescale_title_small_font_size: 14,
    md_sys_typescale_title_small_line_height: 20,
    md_sys_typescale_title_small_letter_spacing: 0.10,
}

export default tokens;