import tokens from './tokens.js';

const typography = {
    display_large: {
    fontFamily: tokens.md_sys_typescale_display_large_font_family_name,
    // fontStyle: tokens.md_sys_typescale_display_large_font_family_style,
    // fontWeight: tokens.md_sys_typescale_display_large_font_weight,
    fontSize: tokens.md_sys_typescale_display_large_font_size,
    letterSpacing: tokens.md_sys_typescale_display_large_tracking,
    lineHeight: tokens.md_sys_typescale_display_large_height,
    textTransform: tokens.md_sys_typescale_display_large_text_transform,
    // textDecoration: tokens.md_sys_typescale_display_large_text_decoration,
  },
  display_medium: {
    fontFamily: tokens.md_sys_typescale_display_medium_font_family_name,
    // fontStyle: tokens.md_sys_typescale_display_medium_font_family_style,
    // fontWeight: tokens.md_sys_typescale_display_medium_font_weight,
    fontSize: tokens.md_sys_typescale_display_medium_font_size,
    letterSpacing: tokens.md_sys_typescale_display_medium_tracking,
    lineHeight: tokens.md_sys_typescale_display_medium_height,
    textTransform: tokens.md_sys_typescale_display_medium_text_transform,
    // textDecoration: tokens.md_sys_typescale_display_medium_text_decoration,
  },
  display_small: {
    fontFamily: tokens.md_sys_typescale_display_small_font_family_name,
    // fontStyle: tokens.md_sys_typescale_display_small_font_family_style,
    // fontWeight: tokens.md_sys_typescale_display_small_font_weight,
    fontSize: tokens.md_sys_typescale_display_small_font_size,
    letterSpacing: tokens.md_sys_typescale_display_small_tracking,
    lineHeight: tokens.md_sys_typescale_display_small_height,
    textTransform: tokens.md_sys_typescale_display_small_text_transform,
    // textDecoration: tokens.md_sys_typescale_display_small_text_decoration,
  },
  headline_large: {
    fontFamily: tokens.md_sys_typescale_headline_large_font_family_name,
    // fontStyle: tokens.md_sys_typescale_headline_large_font_family_style,
    // fontWeight: tokens.md_sys_typescale_headline_large_font_weight,
    fontSize: tokens.md_sys_typescale_headline_large_font_size,
    letterSpacing: tokens.md_sys_typescale_headline_large_tracking,
    lineHeight: tokens.md_sys_typescale_headline_large_height,
    textTransform: tokens.md_sys_typescale_headline_large_text_transform,
    // textDecoration: tokens.md_sys_typescale_headline_large_text_decoration,
  },
  headline_medium: {
    fontFamily: tokens.md_sys_typescale_headline_medium_font_family_name,
    // fontStyle: tokens.md_sys_typescale_headline_medium_font_family_style,
    // fontWeight: tokens.md_sys_typescale_headline_medium_font_weight,
    fontSize: tokens.md_sys_typescale_headline_medium_font_size,
    letterSpacing: tokens.md_sys_typescale_headline_medium_tracking,
    lineHeight: tokens.md_sys_typescale_headline_medium_height,
    textTransform: tokens.md_sys_typescale_headline_medium_text_transform,
    // textDecoration: tokens.md_sys_typescale_headline_medium_text_decoration,
  },
  headline_small: {
    fontFamily: tokens.md_sys_typescale_headline_small_font_family_name,
    // fontStyle: tokens.md_sys_typescale_headline_small_font_family_style,
    // fontWeight: tokens.md_sys_typescale_headline_small_font_weight,
    fontSize: tokens.md_sys_typescale_headline_small_font_size,
    letterSpacing: tokens.md_sys_typescale_headline_small_tracking,
    lineHeight: tokens.md_sys_typescale_headline_small_height,
    textTransform: tokens.md_sys_typescale_headline_small_text_transform,
    // textDecoration: tokens.md_sys_typescale_headline_small_text_decoration,
  },
  body_large: {
    fontFamily: tokens.md_sys_typescale_body_large_font_family_name,
    // fontStyle: tokens.md_sys_typescale_body_large_font_family_style,
    // fontWeight: tokens.md_sys_typescale_body_large_font_weight,
    fontSize: tokens.md_sys_typescale_body_large_font_size,
    letterSpacing: tokens.md_sys_typescale_body_large_tracking,
    lineHeight: tokens.md_sys_typescale_body_large_height,
    textTransform: tokens.md_sys_typescale_body_large_text_transform,
    // textDecoration: tokens.md_sys_typescale_body_large_text_decoration,
  },
  body_medium: {
    fontFamily: tokens.md_sys_typescale_body_medium_font_family_name,
    // fontStyle: tokens.md_sys_typescale_body_medium_font_family_style,
    // fontWeight: tokens.md_sys_typescale_body_medium_font_weight,
    fontSize: tokens.md_sys_typescale_body_medium_font_size,
    letterSpacing: tokens.md_sys_typescale_body_medium_tracking,
    lineHeight: tokens.md_sys_typescale_body_medium_height,
    textTransform: tokens.md_sys_typescale_body_medium_text_transform,
    // textDecoration: tokens.md_sys_typescale_body_medium_text_decoration,
  },
  body_small: {
    // fontFamily: tokens.md_sys_typescale_body_small_font_family_name,
    // fontStyle: tokens.md_sys_typescale_body_small_font_family_style,
    // fontWeight: tokens.md_sys_typescale_body_small_font_weight,
    fontSize: tokens.md_sys_typescale_body_small_font_size,
    letterSpacing: tokens.md_sys_typescale_body_small_tracking,
    lineHeight: tokens.md_sys_typescale_body_small_height,
    textTransform: tokens.md_sys_typescale_body_small_text_transform,
    // textDecoration: tokens.md_sys_typescale_body_small_text_decoration,
  },
  label_large: {
    fontFamily: tokens.md_sys_typescale_label_large_font_family_name,
    // fontStyle: tokens.md_sys_typescale_label_large_font_family_style,
    // fontWeight: tokens.md_sys_typescale_label_large_font_weight,
    fontSize: tokens.md_sys_typescale_label_large_font_size,
    letterSpacing: tokens.md_sys_typescale_label_large_tracking,
    lineHeight: tokens.md_sys_typescale_label_large_height,
    textTransform: tokens.md_sys_typescale_label_large_text_transform,
    // textDecoration: tokens.md_sys_typescale_label_large_text_decoration,
  },
  label_medium: {
    fontFamily: tokens.md_sys_typescale_label_medium_font_family_name,
    // fontStyle: tokens.md_sys_typescale_label_medium_font_family_style,
    // fontWeight: tokens.md_sys_typescale_label_medium_font_weight,
    fontSize: tokens.md_sys_typescale_label_medium_font_size,
    letterSpacing: tokens.md_sys_typescale_label_medium_tracking,
    lineHeight: tokens.md_sys_typescale_label_medium_height,
    textTransform: tokens.md_sys_typescale_label_medium_text_transform,
    // textDecoration: tokens.md_sys_typescale_label_medium_text_decoration,
  },
  label_small: {
    fontFamily: tokens.md_sys_typescale_label_small_font_family_name,
    // fontStyle: tokens.md_sys_typescale_label_small_font_family_style,
    // fontWeight: tokens.md_sys_typescale_label_small_font_weight,
    fontSize: tokens.md_sys_typescale_label_small_font_size,
    letterSpacing: tokens.md_sys_typescale_label_small_tracking,
    lineHeight: tokens.md_sys_typescale_label_small_height,
    textTransform: tokens.md_sys_typescale_label_small_text_transform,
    // textDecoration: tokens.md_sys_typescale_label_small_text_decoration,
  },
  title_large: {
    fontFamily: tokens.md_sys_typescale_title_large_font_family_name,
    // fontStyle: tokens.md_sys_typescale_title_large_font_family_style,
    // fontWeight: tokens.md_sys_typescale_title_large_font_weight,
    fontSize: tokens.md_sys_typescale_title_large_font_size,
    letterSpacing: tokens.md_sys_typescale_title_large_tracking,
    lineHeight: tokens.md_sys_typescale_title_large_height,
    textTransform: tokens.md_sys_typescale_title_large_text_transform,
    // textDecoration: tokens.md_sys_typescale_title_large_text_decoration,
  },
  title_medium: {
    fontFamily: tokens.md_sys_typescale_title_medium_font_family_name,
    // fontStyle: tokens.md_sys_typescale_title_medium_font_family_style,
    // fontWeight: tokens.md_sys_typescale_title_medium_font_weight,
    fontSize: tokens.md_sys_typescale_title_medium_font_size,
    letterSpacing: tokens.md_sys_typescale_title_medium_tracking,
    lineHeight: tokens.md_sys_typescale_title_medium_height,
    textTransform: tokens.md_sys_typescale_title_medium_text_transform,
    // textDecoration: tokens.md_sys_typescale_title_medium_text_decoration,
  },
  title_small: {
    fontFamily: tokens.md_sys_typescale_title_small_font_family_name,
    // fontStyle: tokens.md_sys_typescale_title_small_font_family_style,
    // fontWeight: tokens.md_sys_typescale_title_small_font_weight,
    fontSize: tokens.md_sys_typescale_title_small_font_size,
    letterSpacing: tokens.md_sys_typescale_title_small_tracking,
    lineHeight: tokens.md_sys_typescale_title_small_height,
    textTransform: tokens.md_sys_typescale_title_small_text_transform,
    // textDecoration: tokens.md_sys_typescale_title_small_text_decoration,
  }
}  

export default typography;