import typography from './tokens.js';

const typography = {
    display_large: {
    font_family: typography.md_sys_typescale_display_large_font_family_name,
    font_style: typography.md_sys_typescale_display_large_font_family_style,
    font_weight: typography.md_sys_typescale_display_large_font_weight,
    font_size: typography.md_sys_typescale_display_large_font_size,
    letter_spacing: typography.md_sys_typescale_display_large_tracking,
    line_height: typography.md_sys_typescale_display_large_height,
    text_transform: typography.md_sys_typescale_display_large_text_transform,
    text_decoration: typography.md_sys_typescale_display_large_text_decoration,
  },
  display_medium: {
    font_family: typography.md_sys_typescale_display_medium_font_family_name,
    font_style: typography.md_sys_typescale_display_medium_font_family_style,
    font_weight: typography.md_sys_typescale_display_medium_font_weight,
    font_size: typography.md_sys_typescale_display_medium_font_size,
    letter_spacing: typography.md_sys_typescale_display_medium_tracking,
    line_height: typography.md_sys_typescale_display_medium_height,
    text_transform: typography.md_sys_typescale_display_medium_text_transform,
    text_decoration: typography.md_sys_typescale_display_medium_text_decoration,
  },
  display_small: {
    font_family: typography.md_sys_typescale_display_small_font_family_name,
    font_style: typography.md_sys_typescale_display_small_font_family_style,
    font_weight: typography.md_sys_typescale_display_small_font_weight,
    font_size: typography.md_sys_typescale_display_small_font_size,
    letter_spacing: typography.md_sys_typescale_display_small_tracking,
    line_height: typography.md_sys_typescale_display_small_height,
    text_transform: typography.md_sys_typescale_display_small_text_transform,
    text_decoration: typography.md_sys_typescale_display_small_text_decoration,
  },
  headline_large: {
    font_family: typography.md_sys_typescale_headline_large_font_family_name,
    font_style: typography.md_sys_typescale_headline_large_font_family_style,
    font_weight: typography.md_sys_typescale_headline_large_font_weight,
    font_size: typography.md_sys_typescale_headline_large_font_size,
    letter_spacing: typography.md_sys_typescale_headline_large_tracking,
    line_height: typography.md_sys_typescale_headline_large_height,
    text_transform: typography.md_sys_typescale_headline_large_text_transform,
    text_decoration: typography.md_sys_typescale_headline_large_text_decoration,
  },
  headline_medium: {
    font_family: typography.md_sys_typescale_headline_medium_font_family_name,
    font_style: typography.md_sys_typescale_headline_medium_font_family_style,
    font_weight: typography.md_sys_typescale_headline_medium_font_weight,
    font_size: typography.md_sys_typescale_headline_medium_font_size,
    letter_spacing: typography.md_sys_typescale_headline_medium_tracking,
    line_height: typography.md_sys_typescale_headline_medium_height,
    text_transform: typography.md_sys_typescale_headline_medium_text_transform,
    text_decoration: typography.md_sys_typescale_headline_medium_text_decoration,
  },
  headline_small: {
    font_family: typography.md_sys_typescale_headline_small_font_family_name,
    font_style: typography.md_sys_typescale_headline_small_font_family_style,
    font_weight: typography.md_sys_typescale_headline_small_font_weight,
    font_size: typography.md_sys_typescale_headline_small_font_size,
    letter_spacing: typography.md_sys_typescale_headline_small_tracking,
    line_height: typography.md_sys_typescale_headline_small_height,
    text_transform: typography.md_sys_typescale_headline_small_text_transform,
    text_decoration: typography.md_sys_typescale_headline_small_text_decoration,
  },
  body_large: {
    font_family: typography.md_sys_typescale_body_large_font_family_name,
    font_style: typography.md_sys_typescale_body_large_font_family_style,
    font_weight: typography.md_sys_typescale_body_large_font_weight,
    font_size: typography.md_sys_typescale_body_large_font_size,
    letter_spacing: typography.md_sys_typescale_body_large_tracking,
    line_height: typography.md_sys_typescale_body_large_height,
    text_transform: typography.md_sys_typescale_body_large_text_transform,
    text_decoration: typography.md_sys_typescale_body_large_text_decoration,
  },
  body_medium: {
    font_family: typography.md_sys_typescale_body_medium_font_family_name,
    font_style: typography.md_sys_typescale_body_medium_font_family_style,
    font_weight: typography.md_sys_typescale_body_medium_font_weight,
    font_size: typography.md_sys_typescale_body_medium_font_size,
    letter_spacing: typography.md_sys_typescale_body_medium_tracking,
    line_height: typography.md_sys_typescale_body_medium_height,
    text_transform: typography.md_sys_typescale_body_medium_text_transform,
    text_decoration: typography.md_sys_typescale_body_medium_text_decoration,
  },
  body_small: {
    font_family: typography.md_sys_typescale_body_small_font_family_name,
    font_style: typography.md_sys_typescale_body_small_font_family_style,
    font_weight: typography.md_sys_typescale_body_small_font_weight,
    font_size: typography.md_sys_typescale_body_small_font_size,
    letter_spacing: typography.md_sys_typescale_body_small_tracking,
    line_height: typography.md_sys_typescale_body_small_height,
    text_transform: typography.md_sys_typescale_body_small_text_transform,
    text_decoration: typography.md_sys_typescale_body_small_text_decoration,
  },
  label_large: {
    font_family: typography.md_sys_typescale_label_large_font_family_name,
    font_style: typography.md_sys_typescale_label_large_font_family_style,
    font_weight: typography.md_sys_typescale_label_large_font_weight,
    font_size: typography.md_sys_typescale_label_large_font_size,
    letter_spacing: typography.md_sys_typescale_label_large_tracking,
    line_height: typography.md_sys_typescale_label_large_height,
    text_transform: typography.md_sys_typescale_label_large_text_transform,
    text_decoration: typography.md_sys_typescale_label_large_text_decoration,
  },
  label_medium: {
    font_family: typography.md_sys_typescale_label_medium_font_family_name,
    font_style: typography.md_sys_typescale_label_medium_font_family_style,
    font_weight: typography.md_sys_typescale_label_medium_font_weight,
    font_size: typography.md_sys_typescale_label_medium_font_size,
    letter_spacing: typography.md_sys_typescale_label_medium_tracking,
    line_height: typography.md_sys_typescale_label_medium_height,
    text_transform: typography.md_sys_typescale_label_medium_text_transform,
    text_decoration: typography.md_sys_typescale_label_medium_text_decoration,
  },
  label_small: {
    font_family: typography.md_sys_typescale_label_small_font_family_name,
    font_style: typography.md_sys_typescale_label_small_font_family_style,
    font_weight: typography.md_sys_typescale_label_small_font_weight,
    font_size: typography.md_sys_typescale_label_small_font_size,
    letter_spacing: typography.md_sys_typescale_label_small_tracking,
    line_height: typography.md_sys_typescale_label_small_height,
    text_transform: typography.md_sys_typescale_label_small_text_transform,
    text_decoration: typography.md_sys_typescale_label_small_text_decoration,
  },
  title_large: {
    font_family: typography.md_sys_typescale_title_large_font_family_name,
    font_style: typography.md_sys_typescale_title_large_font_family_style,
    font_weight: typography.md_sys_typescale_title_large_font_weight,
    font_size: typography.md_sys_typescale_title_large_font_size,
    letter_spacing: typography.md_sys_typescale_title_large_tracking,
    line_height: typography.md_sys_typescale_title_large_height,
    text_transform: typography.md_sys_typescale_title_large_text_transform,
    text_decoration: typography.md_sys_typescale_title_large_text_decoration,
  },
  title_medium: {
    font_family: typography.md_sys_typescale_title_medium_font_family_name,
    font_style: typography.md_sys_typescale_title_medium_font_family_style,
    font_weight: typography.md_sys_typescale_title_medium_font_weight,
    font_size: typography.md_sys_typescale_title_medium_font_size,
    letter_spacing: typography.md_sys_typescale_title_medium_tracking,
    line_height: typography.md_sys_typescale_title_medium_height,
    text_transform: typography.md_sys_typescale_title_medium_text_transform,
    text_decoration: typography.md_sys_typescale_title_medium_text_decoration,
  },
  title_small: {
    font_family: typography.md_sys_typescale_title_small_font_family_name,
    font_style: typography.md_sys_typescale_title_small_font_family_style,
    font_weight: typography.md_sys_typescale_title_small_font_weight,
    font_size: typography.md_sys_typescale_title_small_font_size,
    letter_spacing: typography.md_sys_typescale_title_small_tracking,
    line_height: typography.md_sys_typescale_title_small_height,
    text_transform: typography.md_sys_typescale_title_small_text_transform,
    text_decoration: typography.md_sys_typescale_title_small_text_decoration,
  }
}  